// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package invoices

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "time"

func Form() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"bg-slate-700 rounded-md w-full p-5 flex flex-col gap-4\" x-data=\"{count:0}\"><div class=\"grid grid-cols-5 gap-3\"><div><label class=\"text-white font-semibold\">Reference</label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(templ.Attributes{"type": "text", "name": "Reference", "class": "w-full rounded-md border p-2 mt-2 bg-slate-600 text-white border-slate-800", "value": "INV-" + time.Now().Format("20060102150405")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div><label class=\"text-white font-semibold\">Date</label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(templ.Attributes{"type": "date", "name": "Date", "class": "w-full rounded-md border p-2 mt-2 h-[43px] bg-slate-600 text-white border-slate-800", "value": time.Now().Format("2006-01-02")}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\"flex gap-3 pb-2 pt-3\"><input type=\"hidden\" name=\"lines\" x-model=\"count\"> <button hx-get=\"/new-line\" hx-include=\"[name=&#39;lines&#39;]\" hx-target=\"#lines-container\" hx-swap=\"beforeend\" hx-trigger=\"click\" @click=\"count++\" class=\"rounded-full bg-green-100 text-green-500 px-3 py-1 hover:bg-green-200 text-sm\">Add Line</button></div><table class=\"mb-2 w-full pt-5 rounded-md\"><thead><tr><th width=\"2%\" scope=\"col\" class=\"px-4 py-3 bg-slate-600 text-left text-xs font-medium text-white uppercase tracking-wider rounded-l-lg\"></th><th scope=\"col\" class=\"px-6 py-3 bg-slate-600 text-left text-xs font-medium text-white uppercase tracking-wider\">Description</th><th width=\"12%\" scope=\"col\" class=\"px-4 py-3 bg-slate-600 text-left text-xs font-medium text-white uppercase tracking-wider\">Unit Price</th><th width=\"12%\" scope=\"col\" class=\"px-4 py-3 bg-slate-600 text-left text-xs font-medium text-white uppercase tracking-wider\">Qty</th><th width=\"15%\" scope=\"col\" class=\"px-4 py-3 bg-slate-600 text-left text-xs font-medium text-white uppercase tracking-wider rounded-r-lg\">Line Total</th></tr></thead> <tbody id=\"lines-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Line("0").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</tbody></table><div class=\"flex justify-end w-full\"><div class=\"flex flex-col gap-3 bg-slate-600 text-white rounded-lg p-4\"><div id=\"subtotal\" class=\"flex items-center gap-2\" hx-post=\"/set-subtotal\" hx-trigger=\"setSubtotal\" hx-target=\"this\"><span>Subtotal:</span> <span>$0.00</span></div><div class=\"flex items-center gap-2\"><label>Discount</label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Input(templ.Attributes{"type": "number", "step": "0.01", "min": "0", "name": "Discount", "class": "w-full rounded-md border bg-slate-700 p-1 text-white border-slate-600", "hx-post": "/set-total", "hx-trigger": "keyup delay:100ms", "hx-target": "#total", "value": "0"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span>%</span></div><div id=\"total\" class=\"flex items-center gap-2\" hx-post=\"/set-total\" hx-trigger=\"setTotal\" hx-target=\"this\"><span>Total:</span> <span>$0.00</span></div></div></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
